FAROSDKDemoApp:
    dir:
        D:\Qt\FAROSDKDemoApp\Debug.x64\FAROSDKDemoApp

FAROOpenDemoApp:
    dir:
        D:\Qt\FAROOpenDemoApp\x64\Debug\FAROOpenDemoApp

FAROLSDemoScans:
    dir:
        D:\Qt\FAROLSDemoScans\Debug.x64\
