FAROSDKDemoApp:
    dir:
        D:\QtWin32\FAROSDKDemoApp\Debug.x64\FAROSDKDemoApp

FAROOpenDemoApp:
    dir:
        D:\QtWin32\FAROOpenDemoApp\x64\Debug\FAROOpenDemoApp

FAROLSDemoScans:
    dir:
        D:\QtWin32\FAROLSDemoScans\Debug.x64\
