LaserQtSystem:
    ip:
        192.168.1.101
    port:
        2000

LaserProcessMachine:
    ip:
        192.168.1.102
    port:
        2000

LaserScanner:
    ip:
        192.168.1.103
    port:
        2000

